### ISSUE TITLE
What is the suggested way to convert the `T` type of a `Quantity{T,D,U}`?

### ISSUE THREAD

**Issue by singularitti** [PainterQubits/Unitful.jl#274]
For example, I want to write
```julia
f(x::Quantity{T,D,U}) where {T,D,U} = eps(x)
```
When `x` is a `Quantity{Float64,D,U}`, this works fine:
```julia
julia> typeof(1.0u"J")
Quantity{Float64,𝐋^2*𝐌*𝐓^-2,Unitful.FreeUnits{(J,),𝐋^2*𝐌*𝐓^-2,nothing}}
```
When it is a `Quantity{Int,D,U}`, it will raise an error:
```julia
julia> eps(1u"J")
ERROR: MethodError: no method matching eps(::Int64)
Closest candidates are:
  eps(::Dates.Time) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/Dates/src/types.jl:362
  eps(::Dates.Date) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/Dates/src/types.jl:361
  eps(::Dates.DateTime) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/Dates/src/types.jl:360
  ...
Stacktrace:
 [1] eps(::Quantity{Int64,𝐋^2*𝐌*𝐓^-2,Unitful.FreeUnits{(J,),𝐋^2*𝐌*𝐓^-2,nothing}}) at /Users/qz/.julia/packages/Unitful/ytsW0/src/qua
ntities.jl:350
 [2] top-level scope at REPL[20]:1
```
Thus, I want always to convert `x` to a `Quantity{Float64,D,U}` before passing to `eps` in `f`.
Is there a Julian way to do that? Is it the following?
```julia
f(x::Quantity{T,D,U}) where {T,D,U} = eps(float(x))
```

**Comment by ajkeller34** [comment]
The last line you suggested would certainly work if that's the behavior you want, of course you don't need to specify the type parameters since you don't use them. 

The behavior you noticed isn't special to `Unitful.Quantity` numbers: consider that `eps(3)` will also error. `eps` isn't defined for anything besides floating-point numbers. In that sense I don't think this is a Unitful issue.
