### ISSUE TITLE
@u_str should make `FreeUnits` and not `Quantity`

### ISSUE THREAD

**Issue by goretkin** [PainterQubits/Unitful.jl#275]
I was a little surprised by

```julia
julia> u"1/s"
1 s^-1

julia> typeof(u"1/s")
Quantity{Int64,𝐓^-1,Unitful.FreeUnits{(s^-1,),𝐓^-1,nothing}}

julia> u"s^1"
s

julia> typeof(u"s^1")
Unitful.FreeUnits{(s,),𝐓,nothing}
```

I wanted `u"1/s"` to be a `FreeUnits` type. I'm not sure if it's intended that e.g. the following is allowed:

```julia
julia> u"3m"
3 m
```

**Comment by ajkeller34** [comment]
I suggest `inv(u"s")` or `u"s^-1"`. All of that is intended behavior, although I'm sure there are aspects of the string macro that could be improved.

**Comment by goretkin** [comment]
Thanks. Feel free to close if the current behavior is what we want.

Is there a reason to allow `u"3m"` when `3u"m"` is possible?

**Comment by ajkeller34** [comment]
`1/s` outside of a string macro is really just `/(::Number, ::Units)`, which is why that returns a Quantity. Consider that `2/s` would pretty clearly be indicating a `Quantity`. It's no different inside the macro.

It doesn't seem to hurt anything in particular to allow numbers inside the macro, and I find it convenient to allow for constructing `Quantity`s with it. Also, this is all being manipulated at parse time since it is a macro, so if we wanted `u"3*m"` not to work, but `u"m^3"` to work, then it would be a little more fiddly to implement I think.
