### ISSUE TITLE
Convert between angular frequency and frequency

### ISSUE THREAD

**Issue by jamesgardner1421** [PainterQubits/Unitful.jl#392]
Is this the intended behaviour when converting units involving angles?
```
julia> ω = 1u"rad*s^-1"
1 rad s^-1

julia> uconvert(u"s^-1", ω)
1 s^-1
```
I believe the correct result should be `1/2π s^-1`. If the conversion is not intended, perhaps a `DimensionError` should be thrown instead?

**Comment by derikk** [comment]
This occurs because radians are defined as dimensionless and numerically equal to 1 on [line 66 of `pkgdefaults.jl`](https://github.com/PainterQubits/Unitful.jl/blob/b44c335c466d4ecf007be5bd3aeb8ee4c5debe58/src/pkgdefaults.jl#L66):
`@unit rad "rad" Radian 1 true`

If you want revolutions per second, you can instead convert to `rps`:

```
julia> ω = 1u"rad/s"
1 rad s⁻¹

julia> uconvert(u"rps", ω)
0.15915494309189535 rps
```

Alternatively, converting to `Hz2π` will get you the same numerical result.

```
julia> uconvert(u"Hz2π", ω)
0.15915494309189535 Hz2π
```

**Comment by jamesgardner1421** [comment]
Ah ok, that makes sense, thanks!

**Comment by cmichelenstrofer** [comment]
@jamesgardner1421 checkout [DimensionfulAngles.jl](https://github.com/cmichelenstrofer/DimensionfulAngles.jl) and in particular [this Equivalence](https://cmichelenstrofer.github.io/DimensionfulAngles.jl/stable/guide/derived/#DimensionfulAngles.Periodic).
