### ISSUE TITLE
Cross platform differences when prettyprinting ^2

### ISSUE THREAD

**Issue by icantbelieveitsnotphysics** [PainterQubits/Unitful.jl#433]
Under linux and windows  ^2 in a unit is printed just like that. Under macos it gets ² instead, which breaks doctests that expect outputs to always be the same across platforms.

Is this behaviour part of unitful and intended, or does it arise somewhere else? I don't actually have a mac to check in person at the moment, but here's the failure report from a github actions CI run:

```
│ ```jldoctest
│ julia> gravity(1u"Mearth", 1u"Rearth")
│ 9.798398133669465 m s^-2
│ ```
│ 
│ Subexpression:
│ 
│ gravity(1u"Mearth", 1u"Rearth")
│ 
│ Evaluated output:
│ 
│ 9.798398133669465 m s⁻²
│ 
│ Expected output:
│ 
│ 9.798398133669465 m s^-2
│ 
│   diff =
│    Warning: Diff output requires color.
│    9.798398133669465 m s^-2s⁻²
```

It would be nice if pretty printing styles were consistent across platforms.

**Comment by sostock** [comment]
Pretty-printing of exponents is by default only used on macOS. This was decided in #297 because other systems’ default fonts don’t render fractional exponents nicely. The default behavior can be changed with the environment variable `UNITFUL_FANCY_EXPONENTS`.

You could make your doctests independent from the printing style by interpolating the value into the docstring, i.e.,
```
julia> gravity(1u"Mearth", 1u"Rearth")
$(9.798398133669465u"m/s^2")
```
instead of
```
julia> gravity(1u"Mearth", 1u"Rearth")
9.798398133669465 m s^-2
```

**Comment by icantbelieveitsnotphysics** [comment]
@sostock yep, that seems to have hit the spot, thanks!
