### ISSUE TITLE
incorrect preferred units conversion with atomic units

### ISSUE THREAD

**Issue by Luapulu** [PainterQubits/Unitful.jl#457]
```Julia
using Unitful

using Unitful: preferunits
using UnitfulAtomic: me_au, e_au

preferunits(u"cm", u"ns", me_au, e_au / u"ns")

@show dimension(upreferred(u"V/cm"))
@show dimension(u"V/cm")

@assert dimension(upreferred(u"V/cm")) == dimension(u"V/cm")

```

results in

```Julia
dimension(upreferred(u"V/cm")) = 𝐋 𝐌 𝐈⁻¹ 𝐓⁻⁴
dimension(u"V/cm") = 𝐋 𝐌 𝐈⁻¹ 𝐓⁻³
ERROR: LoadError: AssertionError: dimension(upreferred(u"V/cm")) == dimension(u"V/cm")
[...]
```

with

```
[1986cc42] Unitful v1.8.0
[a7773ee8] UnitfulAtomic v1.0.0
```

**Comment by Luapulu** [comment]
I've narrowed it down some more. Apparently it's not dealing with the current properly

```Julia
dimension(u"A") # = 𝐈
dimension(e_au / u"ns") # = 𝐈
```

but

```Julia
upreferred(dimension(u"A")) # = e
dimension(upreferred(dimension(u"A"))) # = 𝐈 𝐓
```

**Comment by lukebemish** [comment]
I suspect what is happening here is that you are calling preferunit with a "unit" that is actually more than one unit; since preferunits calls `typeof(unit).parameters[1][1]` on the unit, this results in it only pulling out the first unit, e, since the promotion expects a Unitful.Unit instead of a Unitful.FreeUnits. Given how promotion currently works, I'm not sure if there's an easy fix in Unitful to prevent this.

If you don't want to use upreferred and just want this behavior for promotion (i.e., add a value in Coulombs and a value in e and get a value out in e), then try the same techinique that Unitful.promote_to_derived uses:

`Unitful.promote_unit(::S, ::T) where {S<:Unitful.ChargeFreeUnits, T<:Unitful.ChargeFreeUnits} = e_au`

This hints at a possible solution, which I may look into implementing if I have time; could upreferred be made to use the same units as unit promotion uses? Or, can upreferred be made to allow units of non-pure dimensions?
