### ISSUE TITLE
Data sizes

### ISSUE THREAD

**Issue by jtrakk** [PainterQubits/Unitful.jl#486]
> The [octet](https://en.wikipedia.org/wiki/Octet_(computing)) is a unit of digital information in computing and telecommunications that consists of eight bits. The term is often used when the term byte might be ambiguous, as the byte has historically been used for storage units of a variety of sizes.

Could Unitful.jl have bits and either bytes or octets? Maybe [nibbles](https://en.wikipedia.org/wiki/Nibble) too?

**Comment by sostock** [comment]
There is a PR at https://github.com/PainterQubits/Unitful.jl/pull/419, but it hasn’t been merged because it uses `b` for bits and `B` for Bytes, which is breaking (those symbols are currently used for barn and bel). It’s also not clear whether units of information should have their own dimension or be dimensionless.
