### ISSUE TITLE
How to do reciprocal conversion? 

### ISSUE THREAD

**Issue by jtrakk** [PainterQubits/Unitful.jl#520]
```jl
julia> uconvert(u"hr/mi", 3u"mi/hr")
ERROR: DimensionError: hr mi^-1 and mi hr^-1 are not dimensionally compatible.
```

Is there another function that I can use for this?

**Comment by sostock** [comment]
What result do you expect? Do you just want to invert the value, i.e., calculate `1/(3mi/hr)`?

**Comment by jtrakk** [comment]
On second thought I don't really want a function for this, but maybe the error message could explain more what the problem is. Python's pint says 

> DimensionalityError: Cannot convert from 'minute / meter' ([time] / [length]) to 'meter / minute' ([length] / [time])

which mentions the dimensions in addition to the units. It could even be more explicit and say "these dimensions are reciprocals" or something like that.

**Comment by lukebemish** [comment]
I'm not sure if such a change to the error message is really necessary - after all, it tells you exactly what the issue is, namely, that your values are of differing dimensions. It would be nice, however, to get the dimensions in question printed out in the error message, not just that the units are of differing dimensions.
