### ISSUE TITLE
It might be good to document that `ModelingToolkit`, unlike `DifferentialEquations`, supports `Unitful`

### ISSUE THREAD

**Issue by LebedevRI** [PainterQubits/Unitful.jl#574]
At least, i did not find such documentation just now.
https://github.com/SciML/DifferentialEquations.jl/issues/352#issuecomment-1296392350
https://mtk.sciml.ai/dev/basics/Validation/

**Comment by sostock** [comment]
I think the right place to document this would be in `ModelingToolkit`, not in `Unitful`. And apparently, it is already documented there (following the second link you posted). Can you give a reason why this should be documented in `Unitful` as well?

I don’t think it is feasible to list every single package that supports `Unitful` in the documentation, especially since most packages shouldn’t need any `Unitful`-specific code to do so. So why single out `ModelingToolkit`?

**Comment by LebedevRI** [comment]
Thanks.
