### ISSUE TITLE
Inexact error in convert()

### ISSUE THREAD

**Issue by bc0n** [PainterQubits/Unitful.jl#718]
```julia
julia> using Unitful
julia> f(a::T, b::U) where {T,U} = (a, convert(T,b))
f (generic function with 1 method)
julia> f(1u"mm", 2u"inch")

ERROR: InexactError: Int64(254//5)
Stacktrace:
 [1] Integer
   @ .\rational.jl:129 [inlined]
 [2] convert
   @ C:\Users\BenConrad\.julia\packages\Unitful\R4J37\src\conversion.jl:104 [inlined]
 [3] f(a::Quantity{Int64, 𝐋, Unitful.FreeUnits{…}} , b::Quantity{Int64, 𝐋, Unitful.FreeUnits{…}} )
   @ Main .\REPL[2]:1
 [4] top-level scope
   @ REPL[3]:1
```
In Julia 1.10.3+0.x64.w64.mingw32 via Juliaup, Unitful [1986cc42] v1.19.0

**Comment by sostock** [comment]
Why do you expect this to work? You are trying to convert `2inch` to a quantity with integer value and unit `mm`, but 2 inches is not equal to an integer number of millimeters. You would need a rational or floating-point number of millimeters.

If you want to convert just the unit, use `uconvert(unit(a), b)` instead of `convert(T, b)`. This will return a quantity with units `mm` and a numerical value of type `Rational{Int}`. If you want them both to have the same type, you can use `promote` afterwards.

If you just want both quantities to have the same type (and therefore the same unit), but it doesn't matter which unit it is, you can just call `promote(a, b)` without `uconvert`. This will return values of a common type, with units `m` by default.

**Comment by bc0n** [comment]
Thanks for the explanation, I was trying to stick to plain convert() for a function that would work with or without Unitful but now see this was hare-brained.
