### ISSUE TITLE
How to cite Unitful.jl?

### ISSUE THREAD

**Issue by aelmokadem** [PainterQubits/Unitful.jl#725]
Hi,

I am working on a paper that uses Unitful.jl and wanted to know what would be the proper way to cite the package!

Thanks.

**Comment by sostock** [comment]
Right now, we don’t have a preferred way to cite this package. You can cite the Github repo as a website. For the authors, I would put “Andrew Keller and contributors”.

Opening a Zenodo account to make the package easily citable would be good, but I don’t know whether it is possible, since none of the current maintainers of this package are members of the PainterQubits organization.

**Comment by aelmokadem** [comment]
Thanks @sostock . I can use the Github repo for now.

Best,
Ahmed.
